import { spawn } from "child_process";
import path from "path";
import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { NoteSection } from "@/lib/anthropic";

// Farsi/Arabic script range - if the generated text contains it, render via
// the isolated RTL worker (see scripts/render-rtl-pdf.cjs) instead of the
// Helvetica/LTR path below.
const RTL_SCRIPT = /[؀-ۿ]/;

function isRtl(title: string, sections: NoteSection[]): boolean {
  const sample = [
    title,
    ...sections.flatMap((s) => [
      s.heading,
      ...s.bullets,
      ...(s.questions?.flatMap((q) => [q.question, q.answer, ...(q.options ?? [])]) ?? []),
    ]),
  ].join(" ");
  return RTL_SCRIPT.test(sample);
}

function renderRtlPdf(
  title: string,
  videoUrl: string,
  sections: NoteSection[],
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [
      path.join(process.cwd(), "scripts/render-rtl-pdf.cjs"),
    ]);
    const chunks: Buffer[] = [];
    const errChunks: Buffer[] = [];
    child.stdout.on("data", (c) => chunks.push(c));
    child.stderr.on("data", (c) => errChunks.push(c));
    child.on("error", reject);
    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(Buffer.concat(errChunks).toString() || `render-rtl-pdf exited ${code}`));
        return;
      }
      resolve(Buffer.from(Buffer.concat(chunks).toString(), "base64"));
    });
    child.stdin.write(JSON.stringify({ title, videoUrl, sections }));
    child.stdin.end();
  });
}

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica" },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  source: { fontSize: 9, color: "#666666", marginBottom: 20 },
  section: { marginBottom: 14 },
  heading: { fontSize: 13, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  timestamp: { fontSize: 9, color: "#2563eb", marginBottom: 4 },
  bullet: { flexDirection: "row", marginBottom: 3 },
  bulletDot: { width: 12 },
  bulletText: { flex: 1, lineHeight: 1.4 },
  practiceBlock: { marginTop: 8, paddingLeft: 4 },
  practiceLabel: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#7c3aed",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  question: { marginBottom: 4 },
  questionText: { lineHeight: 1.4 },
  optionText: { lineHeight: 1.4, marginLeft: 12, color: "#333333" },
  answerKeyTitle: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    marginBottom: 16,
  },
  answerBlock: { marginBottom: 10 },
  answerHeading: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 3 },
  answerItem: { marginBottom: 3, lineHeight: 1.4 },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 8,
    color: "#999999",
    textAlign: "center",
  },
});

function optionLetter(index: number): string {
  return String.fromCharCode(65 + index);
}

function NotesDocument({
  title,
  videoUrl,
  sections,
}: {
  title: string;
  videoUrl: string;
  sections: NoteSection[];
}) {
  const hasQuestions = sections.some(
    (s) => s.questions && s.questions.length > 0,
  );

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.source}>{videoUrl}</Text>
        {sections.map((section, i) => (
          <View key={i} style={styles.section} wrap={section.breakable ?? false}>
            <Text style={styles.heading}>{section.heading}</Text>
            {section.timestamp && (
              <Text style={styles.timestamp}>{section.timestamp}</Text>
            )}
            {section.bullets.map((bullet, j) => (
              <View key={j} style={styles.bullet}>
                <Text style={styles.bulletDot}>-</Text>
                <Text style={styles.bulletText}>{bullet}</Text>
              </View>
            ))}
            {section.questions && section.questions.length > 0 && (
              <View style={styles.practiceBlock}>
                <Text style={styles.practiceLabel}>Practice</Text>
                {section.questions.map((q, k) => (
                  <View key={k} style={styles.question}>
                    <Text style={styles.questionText}>
                      {k + 1}. {q.question}
                    </Text>
                    {q.type === "mc" &&
                      q.options?.map((opt, oi) => (
                        <Text key={oi} style={styles.optionText}>
                          {optionLetter(oi)}) {opt}
                        </Text>
                      ))}
                  </View>
                ))}
              </View>
            )}
          </View>
        ))}
        <Text style={styles.footer} fixed>
          Generated by NoteTube
        </Text>
      </Page>
      {hasQuestions && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.answerKeyTitle}>Answer Key</Text>
          {sections.map(
            (section, i) =>
              section.questions &&
              section.questions.length > 0 && (
                <View key={i} style={styles.answerBlock} wrap={false}>
                  <Text style={styles.answerHeading}>{section.heading}</Text>
                  {section.questions.map((q, k) => (
                    <Text key={k} style={styles.answerItem}>
                      {k + 1}. {q.answer}
                    </Text>
                  ))}
                </View>
              ),
          )}
          <Text style={styles.footer} fixed>
            Generated by NoteTube
          </Text>
        </Page>
      )}
    </Document>
  );
}

export async function renderNotesPdf(
  title: string,
  videoUrl: string,
  sections: NoteSection[],
): Promise<Buffer> {
  if (isRtl(title, sections)) {
    return renderRtlPdf(title, videoUrl, sections);
  }
  return renderToBuffer(
    <NotesDocument title={title} videoUrl={videoUrl} sections={sections} />,
  );
}
