import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { NoteSection } from "@/lib/anthropic";

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica" },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  source: { fontSize: 9, color: "#666666", marginBottom: 20 },
  section: { marginBottom: 14 },
  heading: { fontSize: 13, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  timestamp: { fontSize: 9, color: "#2563eb", marginBottom: 4 },
  bullet: { flexDirection: "row", marginBottom: 3 },
  bulletDot: { width: 12 },
  bulletText: { flex: 1, lineHeight: 1.4 },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 8,
    color: "#999999",
    textAlign: "center",
  },
});

function NotesDocument({
  title,
  videoUrl,
  sections,
}: {
  title: string;
  videoUrl: string;
  sections: NoteSection[];
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.source}>{videoUrl}</Text>
        {sections.map((section, i) => (
          <View key={i} style={styles.section} wrap={false}>
            <Text style={styles.heading}>{section.heading}</Text>
            {section.timestamp && (
              <Text style={styles.timestamp}>{section.timestamp}</Text>
            )}
            {section.bullets.map((bullet, j) => (
              <View key={j} style={styles.bullet}>
                <Text style={styles.bulletDot}>-</Text>
                <Text style={styles.bulletText}>{bullet}</Text>
              </View>
            ))}
          </View>
        ))}
        <Text style={styles.footer} fixed>
          Generated by NoteTube
        </Text>
      </Page>
    </Document>
  );
}

export async function renderNotesPdf(
  title: string,
  videoUrl: string,
  sections: NoteSection[],
): Promise<Buffer> {
  return renderToBuffer(
    <NotesDocument title={title} videoUrl={videoUrl} sections={sections} />,
  );
}
