// Renders RTL (e.g. Farsi) note PDFs in a fresh, isolated process.
//
// @react-pdf/renderer's bidi/text-shaping engine (@react-pdf/textkit) has a
// bug where rendering a second RTL document with different text in the same
// process crashes with "Cannot read properties of undefined (reading 'id')"
// inside reorderLine/reorderParagraph - some internal glyph-run cache goes
// stale between calls. A lone first render in a fresh process never hits it,
// so each RTL render gets its own throwaway `node` process instead of
// running in-process like the (unaffected) Latin-script path.
//
// Reads {title, videoUrl, sections} JSON from stdin, writes base64 PDF bytes
// to stdout.

const fs = require("fs");
const path = require("path");
const React = require("react");
const {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
  renderToBuffer,
} = require("@react-pdf/renderer");

function loadFontDataUrl(filename) {
  const buf = fs.readFileSync(path.join(process.cwd(), "src/fonts", filename));
  return `data:font/woff;base64,${buf.toString("base64")}`;
}

Font.register({
  family: "Vazirmatn",
  src: loadFontDataUrl("Vazirmatn-Regular.woff"),
});
Font.register({
  family: "Vazirmatn-Bold",
  src: loadFontDataUrl("Vazirmatn-Bold.woff"),
});

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Vazirmatn", textAlign: "right" },
  title: { fontSize: 18, fontFamily: "Vazirmatn-Bold", textAlign: "right", marginBottom: 4 },
  source: { fontSize: 9, color: "#666666", textAlign: "right", marginBottom: 20 },
  section: { marginBottom: 14 },
  heading: { fontSize: 13, fontFamily: "Vazirmatn-Bold", textAlign: "right", marginBottom: 4 },
  timestamp: { fontSize: 9, color: "#2563eb", textAlign: "right", marginBottom: 4 },
  bullet: { flexDirection: "row-reverse", marginBottom: 3 },
  bulletDot: { width: 12 },
  bulletText: { flex: 1, lineHeight: 1.4, textAlign: "right" },
  practiceBlock: { marginTop: 8, paddingRight: 4 },
  practiceLabel: {
    fontSize: 9,
    fontFamily: "Vazirmatn-Bold",
    color: "#7c3aed",
    textAlign: "right",
    marginBottom: 4,
  },
  question: { marginBottom: 4 },
  questionText: { lineHeight: 1.4, textAlign: "right" },
  optionText: { lineHeight: 1.4, marginRight: 12, textAlign: "right", color: "#333333" },
  answerKeyTitle: { fontSize: 16, fontFamily: "Vazirmatn-Bold", textAlign: "right", marginBottom: 16 },
  answerBlock: { marginBottom: 10 },
  answerHeading: { fontSize: 11, fontFamily: "Vazirmatn-Bold", textAlign: "right", marginBottom: 3 },
  answerItem: { marginBottom: 3, lineHeight: 1.4, textAlign: "right" },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 8,
    color: "#999999",
    textAlign: "center",
  },
});

function optionLetter(index) {
  return String.fromCharCode(65 + index);
}

function buildDocument(title, videoUrl, sections) {
  const hasQuestions = sections.some((s) => s.questions && s.questions.length > 0);
  const e = React.createElement;

  const mainPage = e(
    Page,
    { size: "A4", style: styles.page },
    e(Text, { style: styles.title }, title),
    e(Text, { style: styles.source }, videoUrl),
    ...sections.map((section, i) =>
      e(
        View,
        { key: i, style: styles.section, wrap: section.breakable ?? false },
        e(Text, { style: styles.heading }, section.heading),
        section.timestamp && e(Text, { style: styles.timestamp }, section.timestamp),
        ...section.bullets.map((bullet, j) =>
          e(
            View,
            { key: j, style: styles.bullet },
            e(Text, { style: styles.bulletDot }, "-"),
            e(Text, { style: styles.bulletText }, bullet),
          ),
        ),
        section.questions &&
          section.questions.length > 0 &&
          e(
            View,
            { style: styles.practiceBlock },
            e(Text, { style: styles.practiceLabel }, "تمرین"),
            ...section.questions.map((q, k) =>
              e(
                View,
                { key: k, style: styles.question },
                e(Text, { style: styles.questionText }, `${k + 1}. ${q.question}`),
                q.type === "mc" &&
                  q.options &&
                  q.options.map((opt, oi) =>
                    e(Text, { key: oi, style: styles.optionText }, `${optionLetter(oi)}) ${opt}`),
                  ),
              ),
            ),
          ),
      ),
    ),
    e(Text, { style: styles.footer, fixed: true }, "Generated by NoteTube"),
  );

  const pages = [mainPage];

  if (hasQuestions) {
    pages.push(
      e(
        Page,
        { size: "A4", style: styles.page },
        e(Text, { style: styles.answerKeyTitle }, "پاسخنامه"),
        ...sections.map(
          (section, i) =>
            section.questions &&
            section.questions.length > 0 &&
            e(
              View,
              { key: i, style: styles.answerBlock, wrap: false },
              e(Text, { style: styles.answerHeading }, section.heading),
              ...section.questions.map((q, k) =>
                e(Text, { key: k, style: styles.answerItem }, `${k + 1}. ${q.answer}`),
              ),
            ),
        ),
        e(Text, { style: styles.footer, fixed: true }, "Generated by NoteTube"),
      ),
    );
  }

  return e(Document, null, ...pages);
}

let input = "";
process.stdin.on("data", (chunk) => (input += chunk));
process.stdin.on("end", async () => {
  try {
    const { title, videoUrl, sections } = JSON.parse(input);
    const buf = await renderToBuffer(buildDocument(title, videoUrl, sections));
    process.stdout.write(buf.toString("base64"));
  } catch (err) {
    process.stderr.write(String(err && err.stack ? err.stack : err));
    process.exit(1);
  }
});
